@baseUrl = http://127.0.0.1:8000/api
@event =27
@token = 9|u68pwe0ZnggaOyJo3qd6SHbe4R6LclHnPtIFYcyw07b886c8

### Listar todos los eventos (Catálogo)
GET {{baseUrl}}/events
Accept: application/json

### evento especifico
GET {{baseUrl}}/events/{{event}}
Accept: application/json

### Crear un nuevo evento (Organizar Evento)
POST {{baseUrl}}/events
Content-Type: application/json
Accept: application/json

{
    "title": "Conferencia de Ciberseguridad 2025",
    "description": "Expertos internacionales hablan sobre la proteccion de datos en la nube.",
    "location": "Auditorio de la Facultad de Ingeniería",
    "start_time": "2025-12-30 09:00:00",
    "end_time": "2025-12-30 13:00:00",
    "category_id": 1,
    "type": "CERRADO",
    "max_capacity": 200,
    "available_spots": 200
}

###
### Registro de un nuevo participante
### (Esto creará al usuario y restará el cupo)
POST {{baseUrl}}/events/{{event}}/register
Content-Type: application/json
Accept: application/json

{
    "full_name": "Juan Perez",
    "email": "juan2123@espol.edu.ec"
}

###
### Ver lista de participantes de un evento
GET {{baseUrl}}/events/{{event}}/participants
Accept: application/json

###
### Cancelar registro (Devolver cupo)
DELETE {{baseUrl}}/events/{{event}}/cancel
Content-Type: application/json
Accept: application/json

{
    "email": "diego@espol.edu.ec"
}

### Registro de cuenta (Crear Usuario en el sistema)
# Este es el que te devuelve el token para el login
POST {{baseUrl}}/register
Content-Type: application/json
Accept: application/json

{
    "full_name": "Nuevo Usuario",
    "email": "nuevo2@espol.edu.ec",
    "password": "password123"
}

### Iniciar Sesión (Obtener Token)
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
    "email": "diego@espol.edu.ec",
    "password": "12345678"

}

### Inscribirme a un evento
POST {{baseUrl}}/events/5/register
Authorization: Bearer 9|u68pwe0ZnggaOyJo3qd6SHbe4R6LclHnPtIFYcyw07b886c8
Accept: application/json

### Crear evento
POST {{baseUrl}}/events
Authorization: Bearer 9|u68pwe0ZnggaOyJo3qd6SHbe4R6LclHnPtIFYcyw07b886c8
Content-Type: application/json
Accept: application/json

{
    "title": "Integración de Novatos FCNM",
    "description": "Evento social para conocer a los nuevos estudiantes de la facultad.",
    "location": "Cafetería Central",
    "start_time": "2026-01-23 13:00:00",
    "end_time": "2026-01-23 16:00:00",
    "category_id": 2,
    "type": "ABIERTO",
    "max_capacity": 80
}
### Inscribirme a un evento
GET {{baseUrl}}/myevents
Authorization: Bearer 9|u68pwe0ZnggaOyJo3qd6SHbe4R6LclHnPtIFYcyw07b886c8
Accept: application/json