@baseUrl = http://127.0.0.1:8000/api
@event = 5

### Listar todos los eventos (Catálogo)
GET {{baseUrl}}/events
Accept: application/json


### Crear un nuevo evento (Organizar Evento)
POST {{baseUrl}}/events
Content-Type: application/json
Accept: application/json

{
    "title": "Conferencia de Ciberseguridad 2025",
    "description": "Expertos internacionales hablan sobre la proteccion de datos en la nube.",
    "location": "Auditorio de la Facultad de Ingeniería",
    "start_time": "2025-12-30 09:00:00",
    "end_time": "2025-12-30 13:00:00",
    "category_id": 1,
    "type": "CERRADO",
    "max_capacity": 200,
    "available_spots": 200
}

###
### Registro de un nuevo participante
### (Esto creará al usuario y restará el cupo)
POST {{baseUrl}}/events/{{event}}/register
Content-Type: application/json
Accept: application/json

{
    "full_name": "Juan Perez",
    "email": "juan2123@espol.edu.ec"
}

###
### Ver lista de participantes de un evento
GET {{baseUrl}}/events/{{event}}/participants
Accept: application/json

###
### Cancelar registro (Devolver cupo)
DELETE {{baseUrl}}/events/{{event}}/cancel
Content-Type: application/json
Accept: application/json

{
    "email": "diego@espol.edu.ec"
}